spring:
  application:
    name: income-service
  datasource:
    url: jdbc:h2:mem:incomedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8001
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
