spring:
  application:
    name: category-service
  datasource:
    url: jdbc:h2:mem:categorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true

server:
  port: 8003
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
